function [gEqual] = eq(G1,G2)
%EQ  == Equal for FOTF systems.
    
    if min(size(G1.a)==size(G2.a)) && ...
       min(size(G1.b)==size(G2.b)) && ...
       min(size(G1.na)==size(G2.na)) && ...
       min(size(G1.nb)==size(G2.nb)) && ...
       min(fleq(G1.a,G2.a)) && ...
       min(fleq(G1.b,G2.b)) && ...
       min(fleq(G1.na,G2.na)) && ...
       min(fleq(G1.nb,G2.nb)) && ...
       fleq(G1.ioDelay,G2.ioDelay)
        
       % Systems are equal
       gEqual = true;
       
    else
        
       gEqual = false;
       
    end

end
